@tool
extends MenuButton
class_name ControllerIcons_ModifierButton

signal item_requested(item: MainItems)
signal flair_requested
signal text_requested

var base_modifier : String
var flair_modifier : String

enum MainItems {
	TOKEN_SEPARATOR,
	CHANGE_ICON,
	CHANGE_TEXT,
	FLAIR,

	META_SEPARATOR,
	MOVE_LEFT,
	MOVE_RIGHT,
	REMOVE,
}

@onready var text_icon := get_theme_icon("TextMesh", "EditorIcons")
@onready var flair_icon := get_theme_icon("ArrayMesh", "EditorIcons")

@onready var remove_icon := get_theme_icon("Remove", "EditorIcons")
@onready var left_icon := get_theme_icon("MoveLeft", "EditorIcons")
@onready var right_icon := get_theme_icon("MoveRight", "EditorIcons")

func _ready() -> void:
	flat = false
	get_popup().id_pressed.connect(_popup_item_selected)

func _popup_item_selected(id: int):
	match id:
		MainItems.FLAIR:
			flair_requested.emit()
		MainItems.CHANGE_TEXT:
			text_requested.emit()
		_:
			item_requested.emit(id)

func _icon_popup_item_selected(id: int, menu: PopupMenu):
	base_modifier = "_%d" % (id + 1)
	# We have to manually check a single radio button, because for some
	# reason Godot does not do this automatically in PopupMenu's...?
	for i in menu.item_count:
		menu.set_item_checked(i, i == id)
	_update_modifier()

func _update_modifier() -> void:
	var final_modifier = base_modifier + flair_modifier
	# If modifier is empty, _1 is generated by default; we want to
	# prevent that by injecting a blank space
	if final_modifier.is_empty():
		final_modifier = " "
	(icon as ControllerIconTexture).modifiers = final_modifier

func set_token(token: ControllerIcons.TextureData.Token, path: String, input_type: ControllerIcons.InputType) -> void:
	get_popup().clear(true)
	
	var controller_icon := ControllerIconTexture.new()
	controller_icon.path = path

	if token is ControllerIcons.TextureData.IconToken:
		build_icon(path, input_type, token.index)
		base_modifier = "_%d" % (token.index + 1)
		flair_modifier = "{%s}" % token.flair if not token.flair.is_empty() else ""
	elif token is ControllerIcons.TextureData.TextToken:
		build_text()
		base_modifier = token.text

	icon = controller_icon
	_update_modifier()
	var menu_popup := get_popup()
	menu_popup.add_separator("", MainItems.META_SEPARATOR)
	menu_popup.add_icon_item(left_icon, "Move left", MainItems.MOVE_LEFT)
	menu_popup.add_icon_item(right_icon, "Move right", MainItems.MOVE_RIGHT)
	menu_popup.add_icon_item(remove_icon, "Remove", MainItems.REMOVE)

func set_flair(flair: String) -> void:
	flair_modifier = "{%s}" % flair if not flair.is_empty() else ""
	_update_modifier()

func set_icon_text(text: String) -> void:
	base_modifier = text
	_update_modifier()

func get_modifier() -> String:
	return (icon as ControllerIconTexture).modifiers

func set_left_enabled(enable: bool) -> void:
	get_popup().set_item_disabled(get_popup().get_item_index(MainItems.MOVE_LEFT), !enable)

func set_right_enabled(enable: bool) -> void:
	get_popup().set_item_disabled(get_popup().get_item_index(MainItems.MOVE_RIGHT), !enable)

func build_icon(path: String, input_type: ControllerIcons.InputType, curr_index: int) -> void:
	var menu_popup := get_popup()

	menu_popup.add_separator("Icon Token", MainItems.TOKEN_SEPARATOR)

	if ControllerIcons.get_path_type(path) == ControllerIcons.PathType.INPUT_ACTION:
		var icon_menu_popup := build_icon_menu(path, input_type, curr_index)
		assert(icon_menu_popup.item_count > 0, "Sub icon popup has no icons!")
		menu_popup.add_submenu_node_item("Change icon...", icon_menu_popup, MainItems.CHANGE_ICON)

	menu_popup.add_icon_item(flair_icon, "Flairs", MainItems.FLAIR)

func build_icon_menu(path: String, input_type: ControllerIcons.InputType, curr_index: int) -> PopupMenu:
	var menu := PopupMenu.new()
	menu.add_theme_constant_override("icon_max_width", 32)
	menu.id_pressed.connect(_icon_popup_item_selected.bind(menu))

	if input_type == ControllerIcons.InputType.AUTO:
		input_type = ControllerIcons.get_last_input_type()
	var _filter_func = func(event: InputEvent):
		if input_type == ControllerIcons.InputType.KEYBOARD_MOUSE:
			return event is InputEventKey or event is InputEventMouse
		if input_type == ControllerIcons.InputType.CONTROLLER:
			return event is InputEventJoypadButton or event is InputEventJoypadMotion
		assert(false, "Unsupported InputType %d! Please report" % input_type)
		return false

	for event: InputEvent in ControllerIcons._get_action_events(path).filter(_filter_func):
		var controller_icon := ControllerIconTexture.new()
		controller_icon.path = ControllerIcons._convert_event_to_path(event)
		menu.add_icon_radio_check_item(controller_icon, event.as_text())
	menu.set_item_checked(curr_index, true)

	return menu

func build_text() -> void:
	var menu_popup := get_popup()

	menu_popup.add_separator("Text Token", MainItems.TOKEN_SEPARATOR)
	menu_popup.add_icon_item(text_icon, "Change...", MainItems.CHANGE_TEXT)
